spring:
#  data:
#    mongodb:
##      uri: mongodb://182.254.221.168:27017/users
#      host: 182.254.221.168
#      port: 27017
#      database: admin
#      username: admin
#      password: admin
#  redis:
#    host: 123.60.19.184
#    port: 6379
#    password: root
server:
  port: 8081
my: ${my}
#mtwm-api-threshold:
#  appIdToThresholdStr: 99

